name: tbd_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  cached_network_image:
#  flutter_svg: ^2.0.10+1
  flutter_svg:
  flutter_slidable: ^3.1.1
  pin_code_fields: ^8.0.1
  get_storage: ^2.1.1
  fluttertoast: ^8.2.6
  dotted_border: ^2.1.0
  file_picker: ^8.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  text_marquee: ^0.0.2
  text_scroll: ^0.2.0

  http: ^0.13.4
  dio: ^4.0.4
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  flutter_easyloading: ^3.0.5

  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf



