///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppIcons {
  AppIcons._();

  static const String iconsAmount = 'assets/icons/amount.svg';
  static const String iconsBack = 'assets/icons/back.svg';
  static const String iconsBusiness = 'assets/icons/business.svg';
  static const String iconsCamera = 'assets/icons/camera.svg';
  static const String iconsCart = 'assets/icons/cart.svg';
  static const String iconsConsumer = 'assets/icons/consumer.svg';
  static const String iconsCreateNewAccountBig = 'assets/icons/create_new_account_big.svg';
  static const String iconsDelete = 'assets/icons/delete.svg';
  static const String iconsDeleteBig = 'assets/icons/delete_big.svg';
  static const String iconsDelivered = 'assets/icons/delivered.svg';
  static const String iconsDeliveryDate = 'assets/icons/delivery_date.svg';
  static const String iconsDiscount = 'assets/icons/discount.svg';
  static const String iconsDownArrow = 'assets/icons/down_arrow.svg';
  static const String iconsEdit = 'assets/icons/edit.svg';
  static const String iconsEditDeliveryAddress = 'assets/icons/edit_delivery_address.svg';
  static const String iconsEmail = 'assets/icons/email.svg';
  static const String iconsEyeOpen = 'assets/icons/eye_open.svg';
  static const String iconsEyeSplash = 'assets/icons/eye_splash.svg';
  static const String iconsGallery = 'assets/icons/gallery.svg';
  static const String iconsLocation = 'assets/icons/location.svg';
  static const String iconsLogoutBig = 'assets/icons/logout_big.svg';
  static const String iconsMessage = 'assets/icons/message.svg';
  static const String iconsNotification = 'assets/icons/notification.svg';
  static const String iconsOrderDeliveredBig = 'assets/icons/order_delivered_big.svg';
  static const String iconsOrderId = 'assets/icons/order_id.svg';
  static const String iconsOrderManagement = 'assets/icons/order_management.svg';
  static const String iconsOtpBig = 'assets/icons/otp_big.svg';
  static const String iconsPassword = 'assets/icons/password.svg';
  static const String iconsPasswordBig = 'assets/icons/password_big.svg';
  static const String iconsPerson = 'assets/icons/person.svg';
  static const String iconsPhone = 'assets/icons/phone.svg';
  static const String iconsPlus = 'assets/icons/plus.svg';
  static const String iconsProduct = 'assets/icons/product.svg';
  static const String iconsProductManager = 'assets/icons/product_manager.svg';
  static const String iconsQtyMinus = 'assets/icons/qty_minus.svg';
  static const String iconsQtyPlus = 'assets/icons/qty_plus.svg';
  static const String iconsResetPasswordBig = 'assets/icons/reset_password_big.svg';
  static const String iconsRightArrow = 'assets/icons/right_arrow.svg';
  static const String iconsRoundTick = 'assets/icons/round_tick.svg';
  static const String iconsTick = 'assets/icons/tick.svg';
  static const String iconsTickBig = 'assets/icons/tick_big.svg';
  static const String iconsUpArrow = 'assets/icons/up_arrow.svg';
  static const String iconsUploadImage = 'assets/icons/upload_image.svg';
  static const String iconsUser = 'assets/icons/user.svg';
  static const String iconsVendor = 'assets/icons/vendor.svg';
  static const String emptyProduct = 'assets/icons/empty_product.svg';
  static const String productVendor = 'assets/icons/products_vendor.svg';
  static const String moreVert = 'assets/icons/more_vert.svg';
  static const String popup = 'assets/icons/popup.svg';
  static const String archive = 'assets/icons/archive.png';



}
